DROP DATABASE IF EXISTS department_db;

CREATE DATABASE department_db;

USE department_db;

CREATE TABLE department (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE role (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  title VARCHAR(30) NOT NULL UNIQUE,
  salary DECIMAL NOT NULL,
  department_id INT NOT NULL
);

ALTER TABLE role
ADD FOREIGN KEY (department_id)
REFERENCES department (id)
ON DELETE CASCADE;

CREATE TABLE employee (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  role_id INT NOT NULL,
  manager_id INT
);

ALTER TABLE employee
ADD FOREIGN KEY (manager_id)
REFERENCES employee (id)
ON DELETE CASCADE;

ALTER TABLE employee
ADD FOREIGN KEY (role_id)
REFERENCES role (id)
ON DELETE CASCADE;
